data:
  path: /raid/public/imagenet/train
  size:
    - 128
    - 128
  mode: "RGB"
  interpolation: 2
  is_test: False

data_test:
  path: /raid/public/imagenet/validation
  size:
    - 128
    - 128
  mode: "RGB"
  interpolation: 2
  is_test: true

backbone:
  name: VIT
  image_size:
    - 128
    - 128
  stem_config:
    in_channels: 3
    out_channels: 256
    patch_size: 8
    first_stride: 2
    last_stride: 4
    act_layer: silu
    norm_layer: rmsnorm
  encoder_config:
    size: null
    extra_tokens: null
    num_layers: 8
    num_heads: 8
    hidden_dim: 256
    mlp_dim: 1024
    dropout: 0.0
    act_layer: gelu
    norm_layer: rmsnorm
    pos_token: rope
    frequency: 10000.0
  mask_ratio: 0.0
  num_labels: 1000
  last_pool: half
  mode: full
  skip_freeze_prefixes:
    - head
  path_to_checkpoint: "./checkpoints/mae_minivit_imagenet_epoch=37.ckpt"

loss:
  name: CrossEntropyLoss

trainer:
  batch_size: null
  batch_size_per_gpu: 256
  epochs: 100
  logger_frequency: 20
  mixed_precision: true
  optimizer:
    name: "ADAMW"
    lr: 0.0002
    lr_end: 0.00002
    lr_max: 0.0002
    lr_min_scaled: 0.01
    weight_decay: 0.1
    warmup: 0.01
  seed: 46
  workers_per_gpu: 16
