data:
  path: /raid/public/imagenet/train
  size:
    - 128
    - 128
  mode: "RGB"
  interpolation: 2

mae_encoder:
  name: VIT
  image_size:
    - 128
    - 128
  stem_config:
    in_channels: 3
    out_channels: 256
    patch_size: 8
    first_stride: 2
    last_stride: 4
    act_layer: silu
    norm_layer: rmsnorm
  encoder_config:
    size: null
    extra_tokens: null
    num_layers: 8
    num_heads: 8
    hidden_dim: 256
    mlp_dim: 1024
    dropout: 0.0
    act_layer: gelu
    norm_layer: rmsnorm
    pos_token: rope
    frequency: 10000.0
  mask_ratio: 0.75
  num_labels: null
  last_pool: half

mae_decoder:
  name: MAEDecoder
  image_size:
    - 128
    - 128
  patch_size: 8
  channels: 3
  encoder_dim: 256
  decoder_dim: 512
  mlp_dim: 2048
  num_layers: 4
  num_heads: 16
  pos_token: "rope"

loss:
  name: MSELoss

trainer:
  batch_size: 6144
  batch_size_per_gpu: 512
  epochs: 100
  logger_frequency: 20
  mixed_precision: true
  optimizer:
    name: "adamw"
    lr: 0.0002
    lr_end: 0.0001
    lr_max: 0.0002
    weight_decay: 0.1
    warmup: 0.02
  seed: 46
  workers_per_gpu: 16
